name: sentinel-ci
on:
    push:
    pull_request:
        branches:
            - master
        paths-ignore:
            - '**/README.md'
jobs:
    sentinel:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Sentinel
              uses: bloominlabs/setup-hashicorp-releases@24ba535809adca0a710fd39db83eef75cc90af0e
              with:
                package: sentinel
                version: ^0.18.11

            - name: Sentinel Format
              run: sentinel fmt $(find . -name "*.sentinel" -type f ! -path "*/testdata/*")

            - name: Sentinel Test
              run: sentinel test $(find . -name "*.sentinel" -type f ! -path "*/testdata/*")
